n = int(input())
if(n%2==0):
    print('uuuu        uuuu')
    print('uuuu        uuuu')
    print('uuuu        uuuu')
    print('uuuu        uuuu')
    print('uuuu        uuuu')
    print('   uuuuuuuuuu')
    print('   uuuuuuuuuu')
    print('')
    print('')
    print('nnnnnnnnn      nnnn')
    print('nnnn nnnnn     nnnn')
    print('nnnn  nnnnn    nnnn')
    print('nnnn   nnnnn   nnnn')
    print('nnnn    nnnnn  nnnn')
    print('nnnn     nnnnn nnnn')
    print('nnnn      nnnnnnnnn')
    print('  sssssssssssssss ')
    print('  sssssssssssssss ')
    print('  sssss           ')
    print('  sssss           ')
    print('  sssssssssssssss ')
    print('  sssssssssssssss ')
    print('            sssss ')
    print('            sssss ')
    print('  sssssssssssssss ')
    print('  sssssssssssssss ')
    print('')
    print('')
    print('  sssssssssssssss ')
    print('  sssssssssssssss ')
    print('  sssss     sssss ')
    print('  sssss     sssss ')
    print('  sssssssssssssss ')
    print('  sssssssssssssss ')
    print('  sssss     sssss ')
    print('  sssss     sssss ')
    print('  sssss     sssss ')
    print('')
    print('')
    print('  sssssssssssssss ')
    print('  sssssssssssssss ')
    print('  sssss     sssss ')
    print('  sssss     sssss ')
    print('  sssssssssssssss ')
    print('  sssssssssssssss ')
    print('  sssss     sssss ')
    print('  sssss     sssss ')
    print('  sssss     sssss ')
    print('')
    print('')
    print('  ccccccccccccccc ')
    print('  ccccccccccccccc ')
    print('  ccccc ')
    print('  ccccc ')
    print('  ccccc ')
    print('  ccccc ')
    print('  ccccc ')
    print('  ccccccccccccccc ')
    print('  ccccccccccccccc ')
else:
    print('  hhhhh     hhhhh')
    print('  hhhhh     hhhhh')
    print('  hhhhh     hhhhh')
    print('  hhhhhhhhhhhhhhh')
    print('  hhhhhhhhhhhhhhh')
    print('  hhhhhhhhhhhhhhh')
    print('  hhhhh     hhhhh')
    print('  hhhhh     hhhhh')
    print('  hhhhh     hhhhh')
    print('')
    print('')
    print('  sssssssssssssss ')
    print('  sssssssssssssss ')
    print('  sssss     sssss ')
    print('  sssss     sssss ')
    print('  sssssssssssssss ')
    print('  sssssssssssssss ')
    print('  sssss     sssss ')
    print('  sssss     sssss ')
    print('  sssss     sssss ')
    print('')
    print('')

    print('nnnnnnnnn      nnnn')
    print('nnnn nnnnn     nnnn')
    print('nnnn  nnnnn    nnnn')
    print('nnnn   nnnnn   nnnn')
    print('nnnn    nnnnn  nnnn')
    print('nnnn     nnnnn nnnn')
    print('nnnn      nnnnnnnnn')
    print('')
    print('')
    print('  sssssssssssssss ')
    print('  sssssssssssssss ')
    print('  sssss     sssss ')
    print('  sssss     sssss ')
    print('  sssssssssssssss ')
    print('  sssssssssssssss ')
    print('  sssss     sssss ')
    print('  sssss     sssss ')
    print('  sssss     sssss ')
    print('')
    print('')
    print('nnnnnnnnn      nnnn')
    print('nnnn nnnnn     nnnn')
    print('nnnn  nnnnn    nnnn')
    print('nnnn   nnnnn   nnnn')
    print('nnnn    nnnnn  nnnn')
    print('nnnn     nnnnn nnnn')
    print('nnnn      nnnnnnnnn')
